ALTER TABLE zone
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE schedule
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE profile
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE access_card
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE door
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE device
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

UPDATE zone SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL;
UPDATE schedule SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL;
UPDATE profile SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL;
UPDATE access_card SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL;
UPDATE door SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL;
UPDATE device SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL;
